# Generated by Django 5.1.1 on 2025-08-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_humanbodycheck_userinfo_sdcorientationfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdcorientationfeedback',
            old_name='date_of_training',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='sdcorientationfeedback',
            old_name='temp_id',
            new_name='desig_category',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='best',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='better',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='good',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='not_understood',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='trainee_signature',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='trainer_name',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='training_incharge_signature',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='very_good',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='photo',
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='card_no',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='guardian_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='joining_date',
            field=models.DateField(default='2025-08-05'),
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='pay_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='section',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='sdcorientationfeedback',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
