# Generated by Django 5.1.1 on 2025-08-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_rename_date_of_training_sdcorientationfeedback_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='name',
        ),
    ]
