# Generated by Django 5.1.1 on 2025-08-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_curriculum_trainer_name_training_category_venues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMultiSkilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled'), ('inprogress', 'In Progress'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
            ],
        ),
    ]
