# Generated by Django 5.2.4 on 2025-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_newmultiskilling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmultiskilling',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='newmultiskilling',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
