# Generated by Django 5.1 on 2025-08-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_rename_date_newmultiskilling_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanchouExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShokuchouExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sho_question', models.TextField()),
                ('sho_option_a', models.CharField(max_length=255)),
                ('sho_option_b', models.CharField(max_length=255)),
                ('sho_option_c', models.CharField(max_length=255)),
                ('sho_option_d', models.CharField(max_length=255)),
                ('sho_correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='shotrainingcontent',
            old_name='description',
            new_name='sho_description',
        ),
        migrations.RemoveField(
            model_name='hantrainingcontent',
            name='han_content',
        ),
        migrations.RemoveField(
            model_name='shotrainingcontent',
            name='sho_content',
        ),
        migrations.CreateModel(
            name='HanSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('han_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='app1.hancontent')),
            ],
        ),
        migrations.AddField(
            model_name='hantrainingcontent',
            name='han_subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app1.hansubtopic'),
        ),
        migrations.CreateModel(
            name='ShoSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sho_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sho_subtopics', to='app1.shocontent')),
            ],
        ),
        migrations.AddField(
            model_name='shotrainingcontent',
            name='sho_subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sho_materials', to='app1.shosubtopic'),
        ),
        migrations.CreateModel(
            name='HanchouExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='hanchou', editable=False, max_length=50)),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('total_questions', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_mark_percent', models.PositiveSmallIntegerField(default=70)),
                ('passed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hanchou_results', to='app1.employeemaster')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('score__lte', models.F('total_questions'))), name='score_lte_total_questions')],
            },
        ),
        migrations.CreateModel(
            name='ShokuchouExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sho_exam_name', models.CharField(default='shokuchou', editable=False, max_length=50)),
                ('sho_started_at', models.DateTimeField()),
                ('sho_submitted_at', models.DateTimeField()),
                ('sho_total_questions', models.PositiveIntegerField()),
                ('sho_score', models.PositiveIntegerField()),
                ('sho_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sho_pass_mark_percent', models.PositiveSmallIntegerField(default=70)),
                ('sho_passed', models.BooleanField(default=False)),
                ('sho_remarks', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shokuchou_results', to='app1.employeemaster')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('sho_score__lte', models.F('sho_total_questions'))), name='sho_score_lte_total_questions')],
            },
        ),
    ]
