# Generated by Django 5.1 on 2025-08-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_hanchouexamquestion_shokuchouexamquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBatch',
            fields=[
                ('batch_id', models.CharField(help_text='e.g., BATCH-070824', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active batches appear in the attendance dropdown.')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='batch_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Training day number (1-6)')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('attendance_date', models.DateField(blank=True, help_text='The calendar date this attendance was recorded', null=True)),
                ('date_marked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app1.userinfo')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app1.trainingbatch')),
            ],
            options={
                'ordering': ['batch', 'user', 'day_number'],
                'unique_together': {('user', 'batch', 'day_number')},
            },
        ),
    ]
