# Generated by Django 5.2.5 on 2025-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_trainingbatch_userinfo_batch_id_trainingattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelthreeqaojtscore',
            name='score',
            field=models.IntegerField(choices=[(10, 'OK'), (0, 'Not OK')]),
        ),
    ]
