# Generated by Django 5.2.5 on 2025-08-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_alter_levelthreeqaojtscore_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelthreetraineeinfo',
            old_name='trainee_Id',
            new_name='trainee_id',
        ),
    ]
