# Generated by Django 5.2.5 on 2025-08-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_rename_trainee_id_levelthreetraineeinfo_trainee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopfloor_name', models.CharField(max_length=100)),
                ('factory_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_floors', to='app1.factorystructure')),
            ],
        ),
        migrations.CreateModel(
            name='LineStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
                ('shop_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app1.shopfloor')),
            ],
        ),
        migrations.CreateModel(
            name='StationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.linestructure')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_production_plan', models.PositiveIntegerField()),
                ('total_production_actual', models.PositiveIntegerField(default=0)),
                ('total_operators_required_plan', models.PositiveIntegerField(default=0)),
                ('total_operators_required_actual', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l1', models.PositiveIntegerField(default=0, verbose_name='CTQ Plan L1')),
                ('ctq_plan_l2', models.PositiveIntegerField(default=0, verbose_name='CTQ Plan L2')),
                ('ctq_plan_l3', models.PositiveIntegerField(default=0, verbose_name='CTQ Plan L3')),
                ('ctq_plan_l4', models.PositiveIntegerField(default=0, verbose_name='CTQ Plan L4')),
                ('ctq_plan_total', models.PositiveIntegerField(default=0, verbose_name='CTQ Plan Total')),
                ('ctq_actual_l1', models.PositiveIntegerField(default=0, verbose_name='CTQ Actual L1')),
                ('ctq_actual_l2', models.PositiveIntegerField(default=0, verbose_name='CTQ Actual L2')),
                ('ctq_actual_l3', models.PositiveIntegerField(default=0, verbose_name='CTQ Actual L3')),
                ('ctq_actual_l4', models.PositiveIntegerField(default=0, verbose_name='CTQ Actual L4')),
                ('ctq_actual_total', models.PositiveIntegerField(default=0, verbose_name='CTQ Actual Total')),
                ('pdi_plan_l1', models.PositiveIntegerField(default=0, verbose_name='PDI Plan L1')),
                ('pdi_plan_l2', models.PositiveIntegerField(default=0, verbose_name='PDI Plan L2')),
                ('pdi_plan_l3', models.PositiveIntegerField(default=0, verbose_name='PDI Plan L3')),
                ('pdi_plan_l4', models.PositiveIntegerField(default=0, verbose_name='PDI Plan L4')),
                ('pdi_plan_total', models.PositiveIntegerField(default=0, verbose_name='PDI Plan Total')),
                ('pdi_actual_l1', models.PositiveIntegerField(default=0, verbose_name='PDI Actual L1')),
                ('pdi_actual_l2', models.PositiveIntegerField(default=0, verbose_name='PDI Actual L2')),
                ('pdi_actual_l3', models.PositiveIntegerField(default=0, verbose_name='PDI Actual L3')),
                ('pdi_actual_l4', models.PositiveIntegerField(default=0, verbose_name='PDI Actual L4')),
                ('pdi_actual_total', models.PositiveIntegerField(default=0, verbose_name='PDI Actual Total')),
                ('other_plan_l1', models.PositiveIntegerField(default=0, verbose_name='Other Plan L1')),
                ('other_plan_l2', models.PositiveIntegerField(default=0, verbose_name='Other Plan L2')),
                ('other_plan_l3', models.PositiveIntegerField(default=0, verbose_name='Other Plan L3')),
                ('other_plan_l4', models.PositiveIntegerField(default=0, verbose_name='Other Plan L4')),
                ('other_plan_total', models.PositiveIntegerField(default=0, verbose_name='Other Plan Total')),
                ('other_actual_l1', models.PositiveIntegerField(default=0, verbose_name='Other Actual L1')),
                ('other_actual_l2', models.PositiveIntegerField(default=0, verbose_name='Other Actual L2')),
                ('other_actual_l3', models.PositiveIntegerField(default=0, verbose_name='Other Actual L3')),
                ('other_actual_l4', models.PositiveIntegerField(default=0, verbose_name='Other Actual L4')),
                ('other_actual_total', models.PositiveIntegerField(default=0, verbose_name='Other Actual Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factorystructure')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.linestructure')),
                ('shop_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.shopfloor')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stationstructure')),
            ],
        ),
    ]
