# Generated by Django 5.2.1 on 2025-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_newdepartment_newfactory_newline_newworkstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
