# Generated by Django 5.2.4 on 2025-08-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_newdepartment_newfactory_newline_newworkstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltwoqatraineeinfo',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='app1.leveltwoqualityline'),
        ),
        migrations.AlterField(
            model_name='leveltwoqualityline',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveltwolines', to='app1.leveltwoquality'),
        ),
        migrations.CreateModel(
            name='LevelTwoQualitySubStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substations', to='app1.leveltwoqualityline')),
            ],
        ),
        migrations.AddField(
            model_name='leveltwoqatraineeinfo',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='app1.leveltwoqualitysubstation'),
        ),
    ]
