# Generated by Django 5.2.5 on 2025-08-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_alter_leveltwoqatraineeinfo_line_and_more'),
        ('app1', '0048_employeemaster_is_active_employeemaster_read'),
    ]

    operations = [
    ]
