# Generated by Django 5.2.4 on 2025-08-27 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_alter_leveltwoqatraineeinfo_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelThreeQualitySubStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelthree_substations', to='app1.levelthreequalityline')),
            ],
        ),
        migrations.AddField(
            model_name='levelthreeqatraineeinfo',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='app1.levelthreequalitysubstation'),
        ),
    ]
