# Generated by Django 5.2.5 on 2025-08-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_merge_20250826_1742'),
        ('app1', '0050_alter_levelthreeojtscore_score_and_more'),
    ]

    operations = [
    ]
