# Generated by Django 5.2.5 on 2025-09-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='attrition_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Attrition rate in percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_actual_l1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_actual_l2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_actual_l3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_actual_l4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_plan_l1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_plan_l2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_plan_l3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='bifurcation_plan_l4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='gap_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='gap_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='grand_total_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='grand_total_plan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
