# Generated by Django 5.1 on 2025-09-04 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_productionplan_attrition_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_mode', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_production_plan', models.PositiveIntegerField(default=0)),
                ('total_production_actual', models.PositiveIntegerField(default=0)),
                ('total_operators_required_plan', models.PositiveIntegerField(default=0)),
                ('total_operators_required_actual', models.PositiveIntegerField(default=0)),
                ('attrition_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('absenteeism_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Absenteeism rate in percentage (e.g., 5.5 for 5.5%)', max_digits=5)),
                ('ctq_plan_l1', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l2', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l3', models.PositiveIntegerField(default=0)),
                ('ctq_plan_l4', models.PositiveIntegerField(default=0)),
                ('ctq_plan_total', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l1', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l2', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l3', models.PositiveIntegerField(default=0)),
                ('ctq_actual_l4', models.PositiveIntegerField(default=0)),
                ('ctq_actual_total', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l1', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l2', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l3', models.PositiveIntegerField(default=0)),
                ('pdi_plan_l4', models.PositiveIntegerField(default=0)),
                ('pdi_plan_total', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l1', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l2', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l3', models.PositiveIntegerField(default=0)),
                ('pdi_actual_l4', models.PositiveIntegerField(default=0)),
                ('pdi_actual_total', models.PositiveIntegerField(default=0)),
                ('other_plan_l1', models.PositiveIntegerField(default=0)),
                ('other_plan_l2', models.PositiveIntegerField(default=0)),
                ('other_plan_l3', models.PositiveIntegerField(default=0)),
                ('other_plan_l4', models.PositiveIntegerField(default=0)),
                ('other_plan_total', models.PositiveIntegerField(default=0)),
                ('other_actual_l1', models.PositiveIntegerField(default=0)),
                ('other_actual_l2', models.PositiveIntegerField(default=0)),
                ('other_actual_l3', models.PositiveIntegerField(default=0)),
                ('other_actual_l4', models.PositiveIntegerField(default=0)),
                ('other_actual_total', models.PositiveIntegerField(default=0)),
                ('bifurcation_plan_l1', models.PositiveIntegerField(default=0)),
                ('bifurcation_plan_l2', models.PositiveIntegerField(default=0)),
                ('bifurcation_plan_l3', models.PositiveIntegerField(default=0)),
                ('bifurcation_plan_l4', models.PositiveIntegerField(default=0)),
                ('bifurcation_actual_l1', models.PositiveIntegerField(default=0)),
                ('bifurcation_actual_l2', models.PositiveIntegerField(default=0)),
                ('bifurcation_actual_l3', models.PositiveIntegerField(default=0)),
                ('bifurcation_actual_l4', models.PositiveIntegerField(default=0)),
                ('grand_total_plan', models.PositiveIntegerField(default=0)),
                ('grand_total_actual', models.PositiveIntegerField(default=0)),
                ('gap_plan', models.IntegerField(default=0)),
                ('gap_actual', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factorystructure')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.linestructure')),
                ('shop_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.shopfloor')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stationstructure')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'line', 'station')},
            },
        ),
    ]
